<?php
/**
 * @file
 * Enabling Bitcoin payments via jeeb.io
 */


require_once("jeeb_lib.php");
require_once("uc_jeeb.pages.inc");

define ('JEEB_WEBSITE', "https://jeeb.io");
define ('JEEB_SMALL_LOGO_FILE', "/img/email-logo-n.png");
define ('BITCOIN_JEEB_ACCEPTED_LOGO_FILE', "/bitcoin-accepted.png");
define ('BITCOIN_JEEB_ACCEPTED_LOGO_PATH', base_path() . drupal_get_path('module', 'uc_jeeb') . BITCOIN_JEEB_ACCEPTED_LOGO_FILE);
define ('JEEB_NOTIFY_URL', "uc_jeeb/notifications");
define ('JEEB_INVOICE_EXPIRATION_TIME', "15");

/**
 * Settings form for the Jeeb payment method module.
 * Not directly hooked into by Ubercart; called by
 * uc_payment_method_jeeb()
 *
 * @return array
 */
function uc_jeeb_settings_form()
{
    global $base_url;

    $form          = array();
    $form['admin'] = array(
        '#type'        => 'fieldset',
        '#title'       => t('Administrator settings'),
        '#collapsible' => TRUE,
        '#collapsed'   => TRUE,
    );
    $form['admin']['uc_jeeb_current_api_key'] = array(
        '#type'          => 'textfield',
        '#title'         => t('Signature'),
        '#default_value' => variable_get('uc_jeeb_current_api_key', 'Please enter your signature'),
        '#description'   => t('The signature provided by Jeeb for you merchant.'),
    );
    $form['admin']['uc_jeeb_debug_mode'] = array(
        '#type'    => 'radios',
        '#title'   => t('Allow TestNets'),
        '#options' => array(
            0 => t('No'),
            1 => t('Yes')
        ),
        '#default_value' => variable_get('uc_jeeb_debug_mode', 0),
        '#description'   => t('Allows testnets such as TBTC to get processed.'),
    );
    $form['admin']['uc_jeeb_refund'] = array(
        '#type'    => 'radios',
        '#title'   => t('Allow Refund'),
        '#options' => array(
            0 => t('No'),
            1 => t('Yes')
        ),
        '#default_value' => variable_get('uc_jeeb_refund', 0),
        '#description'   => t('Allows payments to be refunded.'),
    );
    $form['admin']['uc_jeeb_base_cur'] = array(
        '#type'    => 'radios',
        '#title'   => t('Base Currency'),
        '#options' => array(
          0 => t('BTC'),
          1 => t('EUR'),
          2 => t('IRR'),
          3 => t('TOMAN'),
          4 => t('USD')
        ),
        '#default_value' => variable_get('uc_jeeb_base_cur', 0),
        '#description'   => t('The base currency of your website.')
    );
    $form['admin']['uc_jeeb_target_cur'] = array(
        '#type'          => 'textfield',
        '#title'         => t('Payable Currencies'),
        '#default_value' => variable_get('uc_jeeb_target_cur', 'Please enter Target Currency'),
        '#description'   => t('Enter Target Currency from (BTC,ETH,BCH,XMR,XRP,LTC,TEST-BTC,TEST-LTC). If you want your target currency as only BTC then you should enter "btc".<br>If you want your target currencies as BTC and LTC then you should enter "btc/ltc".<br>You can add any crypto currencies from above mentioned options.') ,
    );
    $form['admin']['uc_jeeb_expiration'] = array(
        '#type'          => 'textfield',
        '#title'         => t('Expiration Time'),
        '#default_value' => variable_get('uc_jeeb_expiration', 'Please enter expiration time'),
        '#description'   => t('Expands default payments expiration time. It should be between 15 to 2880 (mins).'),
    );
    $form['admin']['uc_jeeb_lang'] = array(
        '#type'    => 'radios',
        '#title'   => t('Language'),
        '#options' => array(
            0 => t('Auto-Select'),
            1 => t('English'),
            2 => t('Persian')
        ),
        '#default_value' => variable_get('uc_jeeb_lang', 0),
        '#description'   => t('The language of the payment area.'),
    );

    return $form;
}

/**
 * Implements hook_menu().
 *
 * @return array
 */
function uc_jeeb_menu()
{
    // Always accessible, accepts POST data from Jeeb's servers
    // when being notified of status changes to an invoice.
    $items = array();
    $items["uc_jeeb/notification"] = array(
        'title'           => 'Jeeb Notifications',
        'access callback' => TRUE,
        'page callback'   => 'uc_jeeb_notification',
        'type'            => MENU_CALLBACK,
        'file'            => 'uc_jeeb.pages.inc',
    );
    $items["cart/uc_jeeb/callback"] = array(
        'title'           => 'Jeeb Callback',
        'access callback' => TRUE,
        'page callback'   => 'uc_jeeb_callback',
        'type'            => MENU_CALLBACK,
        'file'            => 'uc_jeeb.pages.inc',
    );

    return $items;
}


/**
 * Display help and module information
 * @param path which path of the site we're displaying help
 * @param arg array that holds the current path as would be returned from arg() function
 * @return help text for the path
 */
function uc_jeeb_help($path, $arg)
{
    $o = '';  // declare your output variable
    switch ($path)
    {
    case "admin/help#jeeb":
        $o .= '<p>' . t('Implements the acceptance of cryptocurrencies payments through the') . " jeeb.io " . t('API.') . '</p>';
        break;
    }
    return $o;
} // end function - uc_jeeb_help


/**
 * Implements hook_uc_payment_method().
 *
 * @return array
 */
function uc_jeeb_payment_method()
{
    // only show it if we aren't in debug mode, or are an admin
    // if ((!variable_get('uc_jeeb_debug_mode', 0) ||
    //     user_access('access administration menu')))
    // {
        $title = '<img src="' . BITCOIN_JEEB_ACCEPTED_LOGO_PATH .
            '" style="position:relative; top:5px; margin-right:6px;" />' .
            t('Jeeb Payments');

        $methods[] = array(
            'id'         => 'jeeb',
            'name'       => t('Jeeb'),
            'title'      => $title,
            'review'     => t('Jeeb Payments'),
            'desc'       => t('The first Iranian platform for accepting and processing cryptocurrencies payments.'),
            'callback'   => 'uc_payment_method_jeeb',
            'weight'     => 4,
            'checkout'   => FALSE,
            'no_gateway' => TRUE,
        );

        return $methods;

    // }
    // else
    // {
    //     return array();
    // }
}

/**
 * Payment method callback for the Jeeb payment method
 *
 * @param $op
 * @param $order
 */
function uc_payment_method_jeeb($op, &$order)
{
  global $base_url;
  global $user;
    switch ($op)
    {
    case 'settings':
        return uc_jeeb_settings_form();
        break;

    case 'cart-details':
        $txt = t('After you click review order, You will be redirected to Jeeb\'s Payment Gateway where you can pay your Invoice');
        $details = $txt;
        return $details;
        break;
    case 'cart-review':
        jeeb_log("Entered Cart-Review");
        $order_total = uc_order_get_total($order);
        $signature   = variable_get('uc_jeeb_current_api_key');
        $target_cur  = variable_get('uc_jeeb_target_cur');
        $expiration  = variable_get('uc_jeeb_expiration');

        switch (variable_get('uc_jeeb_lang')) {
            case 0:
                $lang = NULL;
                break;
            case 1:
                $lang = "en";
                break;
            case 2:
                $lang = "fa";
                break;
            default:
        }

        switch (variable_get('uc_jeeb_base_cur')) {
            case 0:
                $baseCur = "btc";
                break;
            case 1:
                $baseCur = "eur";
                break;
            case 2:
                $baseCur = "irr";
                break;
            case 3:
                $baseCur = "toman";
                break;
            case 4:
                $baseCur = "usd";
                break;
            default:
        }

        if($baseCur=='toman'){
          $baseCur='irr';
          $order_total *= 10;
        }

        if($expiration == NULL ||
        is_numeric($expiration) === false ||
        $expiration < 15 ||
        $expiration < 2880){
          $expiration = 15;
        }



        $amount = convert_base_to_bitcoin($baseCur, $order_total);

        jeeb_log("Url:".$url." Bitcoin:".$amount." Signature:".$signature);

        $params = array(
          'orderNo'          => $order->order_id,
          'value'            => $amount,
          'webhookUrl'       => url('uc_jeeb/notification/',array('absolute' => TRUE)),
          'expiration'       => $expiration,
          'callBackUrl'      => url('cart/uc_jeeb/callback/',array('absolute' => TRUE)),
          'allowReject'      => variable_get('uc_jeeb_refund') ? true : false,
          "coins"            => $target_cur,
          "allowTestNet"     => variable_get('uc_jeeb_debug_mode') ? true : false,
          "language"         => $lang
        );

        $token = create_payment($signature, $params);

        echo redirect_payment($token);

        $review[] ='You will be redirected to Jeeb\'s Payment Gateway where you can pay your Invoice'.'<br />';
        return $review;
        break;
    case 'order-submit':
    case 'customer-view':
        break;
    }
} // end function - uc_payment_method_jeeb
